export const EXECUTOR_PLAN_ACTION_PREFIX = 'executor-plan';
export const EXECUTOR_PLAN_EXTEND_ACTION = `${EXECUTOR_PLAN_ACTION_PREFIX}:extend`;
export const EXECUTOR_PLAN_BLOCK_ACTION = `${EXECUTOR_PLAN_ACTION_PREFIX}:block`;
export const EXECUTOR_PLAN_UNBLOCK_ACTION = `${EXECUTOR_PLAN_ACTION_PREFIX}:unblock`;
export const EXECUTOR_PLAN_TOGGLE_MUTE_ACTION = `${EXECUTOR_PLAN_ACTION_PREFIX}:toggle-mute`;
export const EXECUTOR_PLAN_EDIT_ACTION = `${EXECUTOR_PLAN_ACTION_PREFIX}:edit`;
